config/routes.rb
Rails.application.routes.draw do
  root to: 'default#index'
  get '/sign_up', to: 'users#new'
  post '/sign_up', to: 'users#create'
  get '/complete', to: 'users#show'

  get '/sign_in', to: 'session#new'
  post '/sign_in', to: 'session#create'
  delete '/sign_out', to: 'session#destroy'

  resources :dashboard, only: [:index]
  resources :todos, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
# == Schema Information
#
# Table name: todos
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  user_id     :integer
#  expired_at  :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  status      :integer          default("default"), not null
#
# Indexes
#
#  index_todos_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Todo < ApplicationRecord
  belongs_to :user

  enum status: { default: 0, done: 1 }

  validates :title, presence: true
  validates :expired_at, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  has_secure_password

  has_many :todos

  validates :email, presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  before_action :set_current_user

  def current_user
    unless session[:user_id]
      return nil
    end

    @current_user = User.find(session[:user_id])
  end

  def set_current_user
    return if @current_user
    @current_user = User.find(session[:user_id]) if session[:user_id]
  end

  def redirect_sign_in
    unless session[:user_id]
      redirect_to sign_in_path
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :redirect_sign_in

  def index
    @todo = Todo.new
  end
end

app/controllers/default_controller.rb
class DefaultController < ApplicationController
  before_action :redirect_dashboard
  
  def index
  end

  private

  def redirect_dashboard
    if session[:user_id]
      redirect_to dashboard_index_path
    end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to dashboard_index_path
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = @current_user.todos.default
    render locals: { todos: @todos }
  end

  def create
    todo = current_user.todos.new(todo_params)
    todo.save
    logger.error todo.errors.to_json
    render locals: { todo: todo }
  end

  def edit
  end

  def update
    todo = Todo.find(params[:id])
    todo.done!
  end

  private

  def todo_params
    params.require(:todo).permit(:title, :description, :expired_at)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      render :show
    else
      render :new
    end
  end

  def show

  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/_form.html.haml
= form_with model: todo do |f|
  %div
    = f.label :title
    = f.text_field :title
  %div
    = f.label :description
    = f.text_area :description
  %div
    = f.label :expired_at
    = f.date_field :expired_at
  %div
    = f.submit 'add'

app/views/dashboard/index.html.haml
#todo-list
  %todo-list

= javascript_pack_tag 'pages/todo-list-index'

app/views/default/index.html.haml
%h2 What can you do?

%p
  You can create and operate ToDo List.

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title TODO App
    %meta{charset: "utf-8"}
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true

  %body
    %header.app-header
      .app-header__content
        %h1.app-header__title
          = link_to 'TODO App', root_path
        %span.app-header__user
          - if current_user
            = current_user.try(:email)
            = link_to 'sign out', sign_out_path, method: :delete
          - else
            = link_to 'sing in', sign_in_path
    .main
      .main__content
        = yield
    = javascript_include_tag 'application'

app/views/session/_form.html.haml
.session-form
  = form_with url: sign_in_path, local: true do |f|
    .session-form__group
      .session-form__input-area
        = f.label :email
        = f.text_field :email, class: 'session-form__input-text'
    .session-form__group
      .session-form__input-area
        = f.label :password
        = f.password_field :password, class: 'session-form__input-text'
    .session-form__group
      .session-form__input-area.session-form__submit-area
        = f.submit 'sign in', class: 'session-form__submit-button'

app/views/session/new.html.haml
.session-body
  = render 'form'

app/views/users/_form.html.haml
.user-form
  = form_with model: user, url: sign_up_path, local: true do |f|
    .user-form__group
      .user-form__input-area
        = f.label :email
        = f.text_field :email, class: 'user-form__input-text'
    .user-form__group
      .user-form__input-area
        = f.label :password
        = f.password_field :password, class: 'user-form__input-text'
    .user-form__group
      .user-form__input-area
        = f.label :password_confirmation
        = f.password_field :password_confirmation, class: 'user-form__input-text'
    .user-form__group
      .user-form__input-area.user-form__submit-area
        = f.submit 'sign up', class: 'user-form__submit-button'

app/views/users/new.html.haml
.user-body
  = render 'form', user: @user

app/views/users/show.html.haml
%div
  = @user.email